### PR TITLE
optional src url for linking to argo cd instance

### PR DESCRIPTION
**Pull request by anderoo**
Hi,

The ArgoCD plugin is super useful, however if the health or readiness status is showing issues then we'd link to quickly access the actual application page on ArgoCD. This PR attempts to address this by adding an optional srcUrl prop to the widget.

I'm relatively rusty with my JS so please indicate any changes you'd like or if there's a different direction I should take here.

Alternatively, we may want to add a prop for extra fields.

### CODE REVIEW

**Comment by iain-b** [comment]
Hi @anderoo, thanks for the PR! This is definitely something we should support; we link out to the parent service in most other plugins. I think the only reason we didn't do that here was for the lack of a reasonable default.
While I am happy to go with a props based approach what do you think about adding this as an optional config field ?
e.g.
```yaml
argocd:
  frontendUrl: https://your-argo-cd/ # Or baseUrl or something
```
Then accessed in the Overview component:
```typescript
const configApi = useApi(configApiRef);
const argoCdUrl = configApi.getOptionalString('argocd.frontendUrl')
```
This would require adding a config schema file to the plugin (e.g. plugins/fossa/config.d.ts).

**Comment by anderoo** [comment]
Hi @iain-b. Thanks for the feedback, didn't think about using the config but it's much nicer thna passing the field down. I've updated the code, LMK if you want this added to the README as well.

**Review by iain-b — DISMISSED** [review]
This is great! Thanks! 

If you have time to update the README be our guest but we can take care of it if not.

**Comment by anderoo** [comment]
> This is great! Thanks!
> 
> If you have time to update the README be our guest but we can take care of it if not.

No worries, I'll update the README now. 

Also have a few questions about another possible PR and wondering what the best channel of communication is? For context, I'm looking into how to expose instance/implementation specific data such as last synched revision.

**Comment by dtuite** [comment]
@anderoo Thanks so much for this PR. 

We have a public Discord channel which you can join to have a discussion with the team: https://discord.gg/2M3cewS6

**Review by iain-b — APPROVED** [review]

**Pull request merged**
